config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :users
  resources :profiles
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, length: { minimum: 4 }
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def create
    @profile = Profile.new(profile_params)

    if @profile.save
      redirect_to @profile
    else
      render 'new'
    end
  end

  def update
    @profile = Profile.find(params[:id])

    if @profile.update(profile_params)
      redirect_to @profile
    else
      render 'edit'
    end
  end

  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    redirect_to profiles_path
  end

  private
  def profile_params
    params.require(:profile).permit(:resume, :interest, :goals,
    :languages, :photo)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path
  end

  private
  def user_params
    params.require(:user).permit(:username, :name, :lastname,
    :email, :phone, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>HELLO WORLD, Talk to Me</h1>
<%= link_to 'My Blog', controller: 'users' %>
<%= link_to 'My Profiles', controller: 'profiles' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T2me</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>

<% if @profile.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@profile.errors.count, "error") %> prohibited
       this profile from being saved:
     </h2>
     <ul>
       <% @profile.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>


  <p>
    <%= f.label :resume %><br>
    <%= f.text_field :resume %>
  </p>

  <p>
    <%= f.label :interest %><br>
    <%= f.text_field :interest %>
  </p>

  <p>
    <%= f.label :goals %><br>
    <%= f.text_field :goals %>
  </p>

  <p>
    <%= f.label :languages %><br>
    <%= f.text_field :languages %>
  </p>

  <p>
    <%= f.label :photo %><br>
    <%= f.text_field :photo %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/profiles/edit.html.erb
<h1>Edit Profile </h1>


<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing Profiles</h1>

<table>
  <tr>
    <th>Resume</th>
    <th>Interest</th>
    <th>Goals</th>
    <th>Languages</th>
    <th>Photo</th>
  </tr>

  <% @profiles.each do |profile| %>
    <tr>
      <td><%= profile.resume %></td>
      <td><%= profile.interest %></td>
      <td><%= profile.goals %></td>
      <td><%= profile.languages %></td>
      <td><%= profile.photo %></td>
      <td><%= link_to 'Show', profile_path(profile) %></td>
      <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
      <td><%= link_to 'Destroy', profile_path(profile),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New Profile </h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p>
  <strong>Resume:</strong>
  <%= @profile.resume %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @profile.interest %>
</p>

<p>
  <strong>Goals:</strong>
  <%= @profile.goals %>
</p>

<p>
  <strong>Languages:</strong>
  <%= @profile.languages %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @profile.photo %>
</p>

<td><%= link_to 'Edit', edit_profile_path(@profile) %></td>
<%= link_to 'Back', profiles_path %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

<% if @user.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@user.errors.count, "error") %> prohibited
       this user from being saved:
     </h2>
     <ul>
       <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>


  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User </h1>


<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Name</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>Phone</th>
    <th>Password</th>
  </tr>

  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.name %></td>
      <td><%= user.lastname %></td>
      <td><%= user.email %></td>
      <td><%= user.phone %></td>
      <td><%= user.password %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Destroy', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>
<%= link_to 'New user', new_user_path %>

app/views/users/new.html.erb
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<td><%= link_to 'Edit', edit_user_path(@user) %></td>
<%= link_to 'Back', users_path %>